# =====================================================================
# 米哈游起动器
# =====================================================================

# 自定义 Wine 的路径
WINER_WINE_PATH = '~/Games/runners/wine-dwproton-wow64-11.0-4/bin/wine'

# 目标 EXE 路径与启动参数
WINER_EXE_PATH = '/mnt/games/elysia/miHoYo/miHoYo_Launcher/launcher.exe'
WINER_EXE_ARGS = ''

# 需要绑定到沙箱中的额外路径
WINER_BIND = '/mnt/games/elysia/miHoYo'
; WINER_RO_BIND = ''

# 穿透深度：
# '0'：仅只读挂载目标 EXE 文件自身。
# '1'：挂载 EXE 所在的目录，使其能读写同目录下的资源（默认）。
# 'n'：向上穿透挂载 n 层父级目录。
WINER_PENETRATE = "1"

# 启用游戏模式
WINER_GAMEMODE = "0"

# =====================================================================
# 通用环境变量（自动穿透送入沙箱）
# =====================================================================

# Wine Prefix 路径
WINEPREFIX = '~/Games/prefixes/mihoyo-launcher_prefix'

# 其他环境变量
MANGOHUD = "0"
WINEDEBUG = "-all"
